openapi: 3.0.0
info:
  title: API v1.0 Documentation
  version: '1.0'
  description: 'Hey, welcome to this chicky documentation (I hope so) ! '
  contact:
    name: Achraf Ghellach
    url: 'https://authdash.com/team/AchrafGhellach'
    email: achraf@maghnify.com
servers:
  - url: 'https://api.authdash.com/v1/'
paths: {}
components:
  schemas: {}
