openapi: 3.0.0
info:
  title: AuthDash API Documentation
  version: '1.0'
  description: "\uD83D\uDC4BHey, welcome to this chicky documentation (I hope so) ! "
  contact:
    name: Achraf Ghellach
    url: 'https://authdash.com/team/AchrafGhellach'
    email: achraf@maghnify.com
servers:
  - url: 'https://api.authdash.com/v1/'
paths: {}
components:
  schemas: {}
